name: Database validation

on:
  push:
    branches: [ master ]
    paths:
    - 'src/db/**.json'
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14'
      - name: Validate db json
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./src/db/schema.json
          INPUT_JSONS: ./src/db/db.json
